name: Publish Backend Docker image

on:
  push:
    branches: [ master ]
    paths:
      - movie-backend/**
      - BackendDockerfile
      - .github/workflows/backend-build.yml

jobs:
  push_to_registry:
    name: Push Backend Docker image to Registery
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: talaatharb/movie-backend:latest
          file: ./BackendDockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max